# move time to the right
right_format = """$time"""

[character]
# success_symbol = "[ï¡](bold green)"
success_symbol = "[ï„µ](bold green)"
# # error_symbol = "[âœ—](bold red) "
error_symbol = "[î‰­](bold red) "
vicmd_symbol = "[î˜«](bold green) "

[battery]
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
format = "[ï¨™$duration](bold yellow)"

[directory]
truncation_length = 5
format = "[ï“ $path](bold blue)[$read_only](red) "
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ğŸŒ± "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[ğŸ’ PICKING](bold red)"

[conda]
format = "[$symbol$environment](green) "

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold green"
format = "[$user]($style) "
show_always = true
