command_timeout = 10000
scan_timeout = 10

[character]
success_symbol = "ğŸš€ "
error_symbol = "ğŸ’£ "
vicmd_symbol = "ğŸƒ "
vimcmd_visual_symbol = "ğŸ”¬ "
vimcmd_replace_one_symbol = "ğŸš§ "
vimcmd_replace_symbol = "ğŸš§ "

[battery]
disabled = true
# charging_symbol = "âš¡ "
# discharging_symbol = "ğŸª« "
# [[battery.display]]
# threshold = 20
# style = "bold red"

[directory]
truncation_length = 5
format = "[$path](bold blue)[$read_only](red) "
truncation_symbol = "â€¦/"

[git_branch]
symbol = "ï˜ "
style = "bold purple"

[git_state]
style = "bold red"
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
style = "bold yellow"
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[conda]
symbol = "conda "
format = "in [$symbol$environment](green) "

[username]
style_user = "bold green"
format = "[$user]($style) "
show_always = false

[sudo]
style = 'bold mauve'
symbol = 'ğŸ§™ '
disabled = false
