command_timeout = 10000
scan_timeout = 10
# move time to the right
right_format = """$time"""

[character]
success_symbol = "ğŸš€ "
error_symbol = "ğŸ’£ "
vicmd_symbol = "ğŸƒ "
vimcmd_visual_symbol = "ğŸ”¬ "
vimcmd_replace_one_symbol = "ğŸš§ "
vimcmd_replace_symbol = "ğŸš§ "

[battery]
charging_symbol = "âš¡ "
discharging_symbol = "ğŸª« "
[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
format = "[ó°”š $duration](bold yellow)"

[directory]
truncation_length = 5
# format = "[ï“ $path](bold blue)[$read_only](red) "
format = "[$path](bold blue)[$read_only](red) "
truncation_symbol = "â€¦/"

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[conda]
symbol = "ó°—¦ "
format = "in [$symbol$environment](green) "

[time]
disabled = false
format = '[ó°”› $time]($style)'
time_format = "%T"

[username]
style_user = "bold green"
format = "[$user]($style) "
show_always = false

[sudo]
style = 'bold mauve'
symbol = 'ğŸ§™ '
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

palette = "catppuccin_mocha"
